In [ ]:
import torch
import math
import numpy as np
import nci
import qcelemental as qcel
from os import listdir
from torchani.nn import SpeciesConverter


In [76]:
dataset = 'NCIA_HB375x10'

ani1x_values = {'radial_cutoff': 5.2,
                'angular_cutoff': 3.5,
                'radial_eta': 16.0,
                'angular_eta': 8.0,
                'radial_dist_divisions': 16,
                'angular_dist_divisions': 4,
                'zeta': 32.0,
                'angle_sections': 8,
                'num_species': 3}

constants = nci.get_constants(**ani1x_values)
data = nci.load_data(dataset)

In [81]:
info

{'charge': 0.0,
 'charge_a': 0.0,
 'charge_b': 0.0,
 'selection_a': slice(0, 8, None),
 'selection_b': slice(8, 15, None),
 'scaling': 0.8,
 'benchmark_Eint': -4.591,
 'benchmark_unit': 'kcal/mol',
 'group': 'OH-O'}

In [80]:
data[:2]

[{'species': tensor([[1, 3, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 3]]),
  'coordinates': tensor([[[-1.6767, -0.1555,  0.0000],
           [-0.9935, -1.1558,  0.0000],
           [-1.1739,  1.0802,  0.0000],
           [-0.1859,  1.0356,  0.0000],
           [-3.1810, -0.1561,  0.0000],
           [-3.5503, -1.1755,  0.0000],
           [-3.5490,  0.3752, -0.8767],
           [-3.5490,  0.3752,  0.8767],
           [ 3.3838, -1.0550,  0.8742],
           [ 3.3838, -1.0550, -0.8742],
           [ 3.7187,  0.4683,  0.0000],
           [ 0.9883, -1.0291,  0.0000],
           [ 3.1362, -0.4486,  0.0000],
           [ 1.6711, -0.1654,  0.0000],
           [ 1.2065,  0.9555,  0.0000]]]),
  'energies': -4.591},
 {'species': tensor([[1, 3, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 3]]),
  'coordinates': tensor([[[-1.6767, -0.1555,  0.0000],
           [-0.9935, -1.1558,  0.0000],
           [-1.1739,  1.0802,  0.0000],
           [-0.1859,  1.0356,  0.0000],
           [-3.1810, -0.1561,  0.0000],
    

In [91]:
example = ['c'] * 5 + ['a'] * 3
index_diff = 5
example

['c', 'c', 'c', 'c', 'c', 'a', 'a', 'a']

In [92]:
example[:index_diff]

['c', 'c', 'c', 'c', 'c']

In [93]:
example[index_diff:]

['a', 'a', 'a']

In [100]:
r_index_diff = len(example) - index_diff

In [98]:
r_example = example[::-1]
r_example

['a', 'a', 'a', 'c', 'c', 'c', 'c', 'c']

In [101]:
r_example[:r_index_diff]

['a', 'a', 'a']

In [102]:
r_example[r_index_diff:]

['c', 'c', 'c', 'c', 'c']

/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/torch/functional.py:1069: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /Users/distiller/project/conda/conda-bld/pytorch_1640812094853/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.cartesian_prod(tensors)  # type: ignore[attr-defined]


In [12]:
species, aevs = AEVC.forward((species, coordinates), index_diff)

In [13]:
species

tensor([[1, 2, 2, 0, 1, 0, 0, 0]])

In [14]:
info

{'charge': 0.0,
 'charge_a': 0.0,
 'charge_b': 0.0,
 'selection_a': slice(0, 8, None),
 'selection_b': slice(8, 15, None),
 'scaling': 0.8,
 'benchmark_Eint': -4.591,
 'benchmark_unit': 'kcal/mol',
 'group': 'OH-O'}

In [15]:
len(species[0])

8

In [19]:
species

tensor([[1, 2, 2, 0, 1, 0, 0, 0]])

In [18]:
aevs

tensor([[[6.8264e-27, 2.7908e-20, 1.1312e-14,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [1.0899e-09, 3.9021e-06, 1.3850e-03,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [5.2499e-33, 1.3771e-25, 3.5809e-19,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         ...,
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]]])

In [16]:
species.shape

torch.Size([1, 8])

In [17]:
aevs.shape

torch.Size([1, 8, 240])

In [20]:
from torchani.data import load

ModuleNotFoundError: No module named 'h5py'

In [31]:
import h5py

AttributeError: module 'h5py' has no attribute 'File'

In [33]:
from torchani.aev import neighbor_pairs_nopbc

In [36]:
atom_index12 = neighbor_pairs_nopbc(species == -1, coordinates, constants['Rcr'])

In [37]:
from torchani.aev import trim_neighbor_pairs

In [39]:
atom_index12_trimmed = trim_neighbor_pairs(atom_index12, index_diff)

In [46]:
atom_index12.view(-1)

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  5,
         5,  5,  6,  6,  6,  7,  7,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,
        10, 10, 10, 10, 11, 11, 11, 12, 12, 13,  1,  2,  3,  4,  5,  6,  7, 11,
        12, 13, 14,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  3,  4,
         5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  4,  5,  6,  7,  8,  9, 10, 11,
        12, 13, 14,  5,  6,  7, 11, 13, 14,  6,  7, 11,  7, 11, 14, 11, 14,  9,
        10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 11, 12, 13, 14, 12, 13, 14, 13,
        14, 14])

In [48]:
atom_index12_trimmed

tensor([[ 0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
          3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  5,  6,  6,  7,  7],
        [11, 12, 13, 14,  8,  9, 10, 11, 12, 13, 14,  8,  9, 10, 11, 12, 13, 14,
          8,  9, 10, 11, 12, 13, 14, 11, 13, 14, 11, 11, 14, 11, 14]])

In [47]:
atom_index12_trimmed.contiguous().view(-1)

tensor([ 0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
         3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  5,  6,  6,  7,  7, 11, 12, 13,
        14,  8,  9, 10, 11, 12, 13, 14,  8,  9, 10, 11, 12, 13, 14,  8,  9, 10,
        11, 12, 13, 14, 11, 13, 14, 11, 11, 14, 11, 14])

In [42]:
atom_index12.shape

torch.Size([2, 82])

In [43]:
atom_index12_trimmed.shape

torch.Size([2, 33])